#config_version=5
mode:
  start_events: superdrop_start
  stop_events: timer_super_drop_timer_complete
  priority: 200

  

timers:
    super_drop_timer:
        start_value: 30
        end_value: 0
        direction: down
        tick_interval: 1s
        start_running: true  
  
variable_player:
    drops_hit:
        score: 500
        drops: 4